# Generated by Django 5.2.1 on 2025-06-01 19:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('drivers', '0005_remove_driverprofile_plate_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='driverprofile',
            name='driver_license',
            field=models.ImageField(blank=True, null=True, upload_to='licenses/'),
        ),
        migrations.AddField(
            model_name='driverprofile',
            name='profile_picture',
            field=models.ImageField(blank=True, null=True, upload_to='profile_pictures/'),
        ),
    ]
