# Generated by Django 5.2.1 on 2025-06-04 15:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('drivers', '0007_remove_driverprofile_profile_picture_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='driverprofile',
            old_name='profile_pic',
            new_name='profile_picture',
        ),
    ]
